# The sample uses an eventfd to exercise dup() without depending on a mounted
# filesystem.  eventfd() currently depends on some networking APIs, so pull in
# reasonable defaults so the sample can be built.
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_POSIX_API=y
CONFIG_EVENTFD=y
CONFIG_NETWORKING=y
CONFIG_NET_TEST=y
CONFIG_TEST_RANDOM_GENERATOR=y
