/*
 * Copyright (c) 2024 Linkedsemi Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_LSQSH_PINCTRL_FUNC_1_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_LSQSH_PINCTRL_FUNC_1_H_

#define GEN_PINMUX_PXYY(FUNC, PX, YY, IDX)        ((FUNC << LS_FUNC_POS) | (PX##YY << LS_PIN_POS) | (IDX << LS_ALT_POS))
#define ADTIM1_CH1_FUNC1_IDX01_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 1)  /* positive function of channel 1 of ADTIM1 */
#define ADTIM1_CH1N_FUNC1_IDX02_PINMUX_PA(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 2)  /* negative function of channel 1 of ADTIM1 */
#define ADTIM1_CH2_FUNC1_IDX03_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 3)  /* positive function of channel 2 of ADTIM1 */
#define ADTIM1_CH2N_FUNC1_IDX04_PINMUX_PA(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 4)  /* negative function of channel 2 of ADTIM1 */
#define ADTIM1_CH3_FUNC1_IDX05_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 5)  /* positive function of channel 3 of ADTIM1 */
#define ADTIM1_CH3N_FUNC1_IDX06_PINMUX_PA(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 6)  /* negative function of channel 3 of ADTIM1 */
#define ADTIM1_CH4_FUNC1_IDX07_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 7)  /* positive function of channel 4 of ADTIM1 */
#define ADTIM1_ETR_FUNC1_IDX08_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 8)  /* external trigger function of ADTIM1 */
#define ADTIM1_BK_FUNC1_IDX09_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 9)  /* break function of ADTIM1 */
#define I2C1_SCL_FUNC1_IDX10_PINMUX_PA(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 10) /* SCL function for IIC 1 */
#define I2C1_SDA_FUNC1_IDX11_PINMUX_PA(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 11) /* SDA function for IIC 1 */
#define I2C1_SMBA_FUNC1_IDX12_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 12) /* SMBA function for IIC 1 */
#define UART1_TXD_FUNC1_IDX13_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 13) /* TX data function for UART 1 */
#define UART1_RXD_FUNC1_IDX14_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 14) /* RX data function for UART 1 */
#define UART1_CTS_N_FUNC1_IDX15_PINMUX_PA(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 15) /* CTS function for UART 1 */
#define UART1_RTS_N_FUNC1_IDX16_PINMUX_PA(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 16) /* RTS function for UART 1 */
#define UART1_CK_FUNC1_IDX17_PINMUX_PA(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 17) /* the clock signal for the uart1 */
#define SPI1_SCK_FUNC1_IDX18_PINMUX_PA(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 18) /* SCK function for SPI 2 */
#define SPI1_NSS_FUNC1_IDX19_PINMUX_PA(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 19) /* chip select function for SPI 1 */
#define SPI1_MOSI_FUNC1_IDX20_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 20) /* MOSI function for SPI 1 */
#define SPI1_MISO_FUNC1_IDX21_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 21) /* MISO function for SPI 1 */
#define SPI1_I2S_FUNC1_IDX22_PINMUX_PA(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 22) /* IIS clock function of SPI 1 */
#define FDCAN_TXD_FUNC1_IDX23_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 23) /* TX data of CAN */
#define FDCAN_RXD_FUNC1_IDX24_PINMUX_PA(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 24) /* RX data of CAN */
#define PS2IF1_CLK_FUNC1_IDX25_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 25) /* ps2if1 clock */
#define PS2IF1_DAT_FUNC1_IDX26_PINMUX_PA(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 26) /* ps2if1 dat */
#define PWM1_FUNC1_IDX27_PINMUX_PA(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 27) /* pwm1 */
#define CAP1_FUNC1_IDX28_PINMUX_PA(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 28) /* cap1 */
#define OWM_FUNC1_IDX29_PINMUX_PA(XX)             GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 29) /* owm */
#define CEC_FUNC1_IDX30_PINMUX_PA(XX)             GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 30) /* cec */
#define PIS_CH1_FUNC1_IDX31_PINMUX_PA(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PA, XX, 31) /* PIS channel 1 output */
#define ADTIM2_CH1_FUNC1_IDX01_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 1)  /* positive function of channel 1 of ADTIM2 */
#define ADTIM2_CH1N_FUNC1_IDX02_PINMUX_PB(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 2)  /* negative function of channel 1 of ADTIM2 */
#define ADTIM2_CH2_FUNC1_IDX03_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 3)  /* positive function of channel 2 of ADTIM2 */
#define ADTIM2_CH2N_FUNC1_IDX04_PINMUX_PB(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 4)  /* negative function of channel 2 of ADTIM2 */
#define ADTIM2_CH3_FUNC1_IDX05_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 5)  /* positive function of channel 3 of ADTIM2 */
#define ADTIM2_CH3N_FUNC1_IDX06_PINMUX_PB(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 6)  /* negative function of channel 3 of ADTIM2 */
#define ADTIM2_CH4_FUNC1_IDX07_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 7)  /* positive function of channel 4 of ADTIM2 */
#define ADTIM2_ETR_FUNC1_IDX08_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 8)  /* external trigger function of ADTIM2 */
#define ADTIM2_BK_FUNC1_IDX09_PINMUX_PB(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 9)  /* break function of ADTIM2 */
#define I2C2_SCL_FUNC1_IDX10_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 10) /* SCL function for IIC 2 */
#define I2C2_SDA_FUNC1_IDX11_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 11) /* SDA function for IIC 2 */
#define I2C2_SMBA_FUNC1_IDX12_PINMUX_PB(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 12) /* SMBA function for IIC 2 */
#define UART2_TXD_FUNC1_IDX13_PINMUX_PB(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 13) /* TX data function for UART 2 */
#define UART2_RXD_FUNC1_IDX14_PINMUX_PB(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 14) /* RX data function for UART 2 */
#define UART2_CTS_N_FUNC1_IDX15_PINMUX_PB(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 15) /* CTS function for UART 2 */
#define UART2_RTS_N_FUNC1_IDX16_PINMUX_PB(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 16) /* RTS function for UART 2 */
#define UART2_CK_FUNC1_IDX17_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 17) /* the clock signal for the uart2 */
#define SPI2_SCK_FUNC1_IDX18_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 18) /* SCK function for SPI 2 */
#define SPI2_NSS_FUNC1_IDX19_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 19) /* chip select function for SPI 2 */
#define SPI2_MOSI_FUNC1_IDX20_PINMUX_PB(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 20) /* MOSI function for SPI 2 */
#define SPI2_MISO_FUNC1_IDX21_PINMUX_PB(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 21) /* MISO function for SPI 2 */
#define SPI2_I2S_FUNC1_IDX22_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 22) /* IIS clock function of SPI 2 */
#define USB1_DP_FUNC1_IDX23_PINMUX_PB(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 23) /* DP function of USB1 */
#define USB1_DM_FUNC1_IDX24_PINMUX_PB(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 24) /* DM function of USB1 */
#define USB1_CID_FUNC1_IDX25_PINMUX_PB(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 25) /* CID function of USB1 */
#define PS2IF2_CLK_FUNC1_IDX26_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 26) /* ps2if2 clock */
#define PS2IF2_DAT_FUNC1_IDX27_PINMUX_PB(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 27) /* ps2if2 dat */
#define PWM2_FUNC1_IDX28_PINMUX_PB(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 28) /* pwm2 */
#define CAP2_FUNC1_IDX29_PINMUX_PB(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 29) /* cap2 */
#define OWM_FUNC1_IDX30_PINMUX_PB(XX)             GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 30) /* owm */
#define CEC_FUNC1_IDX31_PINMUX_PB(XX)             GEN_PINMUX_PXYY(PINMUX_FUNC1, PB, XX, 31) /* cec */
#define GPTIMA1_CH1_FUNC1_IDX01_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 1)  /* channel 1 of GPTIMA */
#define GPTIMA1_CH2_FUNC1_IDX02_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 2)  /* channel 2 of GPTIMA */
#define GPTIMA1_CH3_FUNC1_IDX03_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 3)  /* channel 3 of GPTIMA */
#define GPTIMA1_CH4_FUNC1_IDX04_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 4)  /* channel 4 of GPTIMA */
#define GPTIMA1_ETR_FUNC1_IDX05_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 5)  /* external trigger function of GPTIMA */
#define I2C3_SCL_FUNC1_IDX06_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 6)  /* SCL function for IIC 1 */
#define I2C3_SDA_FUNC1_IDX07_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 7)  /* SDA function for IIC 1 */
#define I2C3_SMBA_FUNC1_IDX08_PINMUX_PC(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 8)  /* SMBA function for IIC 1 */
#define UART3_TXD_FUNC1_IDX09_PINMUX_PC(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 9)  /* TX data function for UART 3 */
#define UART3_RXD_FUNC1_IDX10_PINMUX_PC(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 10) /* RX data function for UART 3 */
#define UART3_CTS_N_FUNC1_IDX11_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 11) /* CTS function for UART 3 */
#define UART3_DSR_N_FUNC1_IDX12_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 12) /* DSR function for UART 3 */
#define UART3_DCD_N_FUNC1_IDX13_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 13) /* DCD function for UART 3 */
#define UART3_RI_N_FUNC1_IDX14_PINMUX_PC(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 14) /* RI function for UART 3 */
#define UART3_RTS_N_FUNC1_IDX15_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 15) /* RTS function for UART 3 */
#define UART3_DTR_N_FUNC1_IDX16_PINMUX_PC(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 16) /* DTR function for UART 3 */
#define UART3_DE_FUNC1_IDX17_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 17) /* DE function for UART 3 */
#define UART3_RE_FUNC1_IDX18_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 18) /* RE function for UART 3 */
#define SPI1_SCK_FUNC1_IDX19_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 19) /* SCK function for SPI 1 */
#define SPI1_NSS_FUNC1_IDX20_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 20) /* chip select function for SPI 1 */
#define SPI1_MOSI_FUNC1_IDX21_PINMUX_PC(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 21) /* MOSI function for SPI 1 */
#define SPI1_MISO_FUNC1_IDX22_PINMUX_PC(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 22) /* MISO function for SPI 1 */
#define SPI1_I2S_FUNC1_IDX23_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 23) /* IIS clock function of SPI 1 */
#define USB1_DP_FUNC1_IDX24_PINMUX_PC(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 24) /* DP function of USB1 */
#define USB1_DM_FUNC1_IDX25_PINMUX_PC(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 25) /* DM function of USB1 */
#define USB1_CID_FUNC1_IDX26_PINMUX_PC(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 26) /* CID function of USB1 */
#define PWM3_FUNC1_IDX27_PINMUX_PC(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 27) /* pwm3 */
#define PWM4_FUNC1_IDX28_PINMUX_PC(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 28) /* pwm4 */
#define CAP3_FUNC1_IDX29_PINMUX_PC(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 29) /* cap3 */
#define CAP4_FUNC1_IDX30_PINMUX_PC(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 30) /* cap4 */
#define PIS_CH2_FUNC1_IDX31_PINMUX_PC(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PC, XX, 31) /* PIS channel 2 output */
#define GPTIMA2_CH1_FUNC1_IDX01_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 1)  /* channel 1 of GPTIMA */
#define GPTIMA2_CH2_FUNC1_IDX02_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 2)  /* channel 2 of GPTIMA */
#define GPTIMA2_CH3_FUNC1_IDX03_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 3)  /* channel 3 of GPTIMA */
#define GPTIMA2_CH4_FUNC1_IDX04_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 4)  /* channel 4 of GPTIMA */
#define GPTIMA2_ETR_FUNC1_IDX05_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 5)  /* external trigger function of GPTIMA */
#define I2C4_SCL_FUNC1_IDX06_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 6)  /* SCL function for IIC 4 */
#define I2C4_SDA_FUNC1_IDX07_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 7)  /* SDA function for IIC 4 */
#define I2C4_SMBA_FUNC1_IDX08_PINMUX_PD(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 8)  /* SMBA function for IIC 4 */
#define UART4_TXD_FUNC1_IDX09_PINMUX_PD(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 9)  /* TX data function for UART 4 */
#define UART4_RXD_FUNC1_IDX10_PINMUX_PD(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 10) /* RX data function for UART 4 */
#define UART4_CTS_N_FUNC1_IDX11_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 11) /* CTS function for UART 4 */
#define UART4_DSR_N_FUNC1_IDX12_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 12) /* DSR function for UART 4 */
#define UART4_DCD_N_FUNC1_IDX13_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 13) /* DCD function for UART 4 */
#define UART4_RI_N_FUNC1_IDX14_PINMUX_PD(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 14) /* RI function for UART 4 */
#define UART4_RTS_N_FUNC1_IDX15_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 15) /* RTS function for UART 4 */
#define UART4_DTR_N_FUNC1_IDX16_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 16) /* DTR function for UART 4 */
#define UART4_DE_FUNC1_IDX17_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 17) /* DE function for UART 4 */
#define UART4_RE_FUNC1_IDX18_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 18) /* RE function for UART 4 */
#define SPI2_SCK_FUNC1_IDX19_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 19) /* SCK function for SPI 1 */
#define SPI2_NSS_FUNC1_IDX20_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 20) /* chip select function for SPI 1 */
#define SPI2_MOSI_FUNC1_IDX21_PINMUX_PD(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 21) /* MOSI function for SPI 1 */
#define SPI2_MISO_FUNC1_IDX22_PINMUX_PD(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 22) /* MISO function for SPI 1 */
#define SPI2_I2S_FUNC1_IDX23_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 23) /* IIS clock function of SPI 1 */
#define MJTAG1_TRST_FUNC1_IDX24_PINMUX_PD(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 24) /* jtag master 1 trst */
#define MJTAG1_TDI_FUNC1_IDX25_PINMUX_PD(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 25) /* jtag master 1 tdi */
#define MJTAG1_TCK_FUNC1_IDX26_PINMUX_PD(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 26) /* jtag master 1 tck */
#define MJTAG1_TMS_FUNC1_IDX27_PINMUX_PD(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 27) /* jtag master 1 tms */
#define MJTAG1_TDO_FUNC1_IDX28_PINMUX_PD(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 28) /* jtag master 1 tdo */
#define DBG_SCL1_FUNC1_IDX29_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 29) /* I2C Debug SCL1 */
#define DBG_SDA1_FUNC1_IDX30_PINMUX_PD(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 30) /* I2C Debug SDA1 */
#define PIS_CH3_FUNC1_IDX31_PINMUX_PD(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PD, XX, 31) /* PIS channel 3 output */
#define GPTIMB1_CH1_FUNC1_IDX01_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 1)  /* channel 1 of GPTIMB */
#define GPTIMB1_CH2_FUNC1_IDX02_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 2)  /* channel 2 of GPTIMB */
#define GPTIMB1_CH3_FUNC1_IDX03_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 3)  /* channel 3 of GPTIMB */
#define GPTIMB1_CH4_FUNC1_IDX04_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 4)  /* channel 4 of GPTIMB */
#define GPTIMB1_ETR_FUNC1_IDX05_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 5)  /* external trigger function of GPTIMB */
#define I2C5_SCL_FUNC1_IDX06_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 6)  /* SCL function for IIC 5 */
#define I2C5_SDA_FUNC1_IDX07_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 7)  /* SDA function for IIC 5 */
#define I2C5_SMBA_FUNC1_IDX08_PINMUX_PE(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 8)  /* SMBA function for IIC 5 */
#define UART5_TXD_FUNC1_IDX09_PINMUX_PE(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 9)  /* TX data function for UART 5 */
#define UART5_RXD_FUNC1_IDX10_PINMUX_PE(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 10) /* RX data function for UART 5 */
#define UART5_CTS_N_FUNC1_IDX11_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 11) /* CTS function for UART 5 */
#define UART5_DSR_N_FUNC1_IDX12_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 12) /* DSR function for UART 5 */
#define UART5_DCD_N_FUNC1_IDX13_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 13) /* DCD function for UART 5 */
#define UART5_RI_N_FUNC1_IDX14_PINMUX_PE(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 14) /* RI function for UART 5 */
#define UART5_RTS_N_FUNC1_IDX15_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 15) /* RTS function for UART 5 */
#define UART5_DTR_N_FUNC1_IDX16_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 16) /* DTR function for UART 5 */
#define UART5_DE_FUNC1_IDX17_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 17) /* DE function for UART 5 */
#define UART5_RE_FUNC1_IDX18_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 18) /* RE function for UART 5 */
#define DBG_HBUS_CLK_FUNC1_IDX19_PINMUX_PE(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 19) /* HBUS clock test output */
#define DBG_SRC_CLK_FUNC1_IDX20_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 20) /* HBUS clock test output */
#define PDM_DAT0_FUNC1_IDX21_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 21) /* pdm channel0 data */
#define PDM_DAT1_FUNC1_IDX22_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 22) /* pdm channel1 data */
#define PDM_CLK_FUNC1_IDX23_PINMUX_PE(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 23) /* pdm clock */
#define MJTAG2_TRST_FUNC1_IDX24_PINMUX_PE(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 24) /* jtag master 2 trst */
#define MJTAG2_TDI_FUNC1_IDX25_PINMUX_PE(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 25) /* jtag master 2 tdi */
#define MJTAG2_TCK_FUNC1_IDX26_PINMUX_PE(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 26) /* jtag master 2 tck */
#define MJTAG2_TMS_FUNC1_IDX27_PINMUX_PE(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 27) /* jtag master 2 tms */
#define MJTAG2_TDO_FUNC1_IDX28_PINMUX_PE(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 28) /* jtag master 2 tdo */
#define DBG_SCL2_FUNC1_IDX29_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 29) /* I2C Debug SCL2 */
#define DBG_SDA2_FUNC1_IDX30_PINMUX_PE(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 30) /* I2C Debug SDA2 */
#define PIS_CH4_FUNC1_IDX31_PINMUX_PE(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PE, XX, 31) /* PIS channel 4 output */
#define GPTIMC1_CH1_FUNC1_IDX01_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 1)  /* positive function of channel 1 of GPTIMC */
#define GPTIMC1_CH1N_FUNC1_IDX02_PINMUX_PF(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 2)  /* negative function of channel 1 of GPTIMC */
#define GPTIMC1_CH2_FUNC1_IDX03_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 3)  /* positive function of channel 2 of GPTIMC */
#define GPTIMC1_BK_FUNC1_IDX04_PINMUX_PF(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 4)  /* break function of GPTIMC */
#define I2C6_SCL_FUNC1_IDX05_PINMUX_PF(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 5)  /* SCL function for IIC 2 */
#define I2C6_SDA_FUNC1_IDX06_PINMUX_PF(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 6)  /* SDA function for IIC 2 */
#define I2C6_SMBA_FUNC1_IDX07_PINMUX_PF(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 7)  /* SMBA function for IIC 2 */
#define UART6_TXD_FUNC1_IDX08_PINMUX_PF(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 8)  /* TX data function for UART 6 */
#define UART6_RXD_FUNC1_IDX09_PINMUX_PF(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 9)  /* RX data function for UART 6 */
#define UART6_CTS_N_FUNC1_IDX10_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 10) /* CTS function for UART 6 */
#define UART6_DSR_N_FUNC1_IDX11_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 11) /* DSR function for UART 6 */
#define UART6_DCD_N_FUNC1_IDX12_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 12) /* DCD function for UART 6 */
#define UART6_RI_N_FUNC1_IDX13_PINMUX_PF(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 13) /* RI function for UART 6 */
#define UART6_RTS_N_FUNC1_IDX14_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 14) /* RTS function for UART 6 */
#define UART6_DTR_N_FUNC1_IDX15_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 15) /* DTR function for UART 6 */
#define UART6_DE_FUNC1_IDX16_PINMUX_PF(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 16) /* DE function for UART 6 */
#define UART6_RE_FUNC1_IDX17_PINMUX_PF(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 17) /* RE function for UART 6 */
#define EMMC2_LED_CTRL_FUNC1_IDX18_PINMUX_PF(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 18) /* SD card communication indicator led */
#define EMMC1_LED_CTRL_FUNC1_IDX19_PINMUX_PF(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 19) /* SD card communication indicator led */
#define PDM_DATA0_FUNC1_IDX20_PINMUX_PF(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 20) /* pdm channel0 data */
#define PDM_DATA1_FUNC1_IDX21_PINMUX_PF(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 21) /* pdm channel1 data */
#define PDM_CLK_FUNC1_IDX22_PINMUX_PF(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 22) /* pdm clock */
#define MJTAG3_TRST_FUNC1_IDX23_PINMUX_PF(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 23) /* jtag master 3 trst */
#define MJTAG3_TDI_FUNC1_IDX24_PINMUX_PF(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 24) /* jtag master 3 tdi */
#define MJTAG3_TCK_FUNC1_IDX25_PINMUX_PF(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 25) /* jtag master 3 tck */
#define MJTAG3_TMS_FUNC1_IDX26_PINMUX_PF(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 26) /* jtag master 3 tms */
#define MJTAG3_TDO_FUNC1_IDX27_PINMUX_PF(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 27) /* jtag master 3 tdo */
#define PWM5_FUNC1_IDX28_PINMUX_PF(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 28) /* pwm5 */
#define PWM6_FUNC1_IDX29_PINMUX_PF(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 29) /* pwm6 */
#define CAP5_FUNC1_IDX30_PINMUX_PF(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 30) /* cap5 */
#define CAP6_FUNC1_IDX31_PINMUX_PF(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PF, XX, 31) /* cap6 */
#define ADTIM1_CH1_FUNC1_IDX01_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 1)  /* positive function of channel 1 of ADTIM1 */
#define ADTIM1_CH1N_FUNC1_IDX02_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 2)  /* negative function of channel 1 of ADTIM1 */
#define ADTIM1_CH2_FUNC1_IDX03_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 3)  /* positive function of channel 2 of ADTIM1 */
#define ADTIM1_CH2N_FUNC1_IDX04_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 4)  /* negative function of channel 2 of ADTIM1 */
#define ADTIM1_CH3_FUNC1_IDX05_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 5)  /* positive function of channel 3 of ADTIM1 */
#define ADTIM1_CH3N_FUNC1_IDX06_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 6)  /* negative function of channel 3 of ADTIM1 */
#define ADTIM1_CH4_FUNC1_IDX07_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 7)  /* positive function of channel 4 of ADTIM1 */
#define ADTIM1_ETR_FUNC1_IDX08_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 8)  /* external trigger function of ADTIM1 */
#define ADTIM1_BK_FUNC1_IDX09_PINMUX_PG(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 9)  /* break function of ADTIM1 */
#define I2C7_SCL_FUNC1_IDX10_PINMUX_PG(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 10) /* SCL function for IIC 7 */
#define I2C7_SDA_FUNC1_IDX11_PINMUX_PG(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 11) /* SDA function for IIC 7 */
#define I2C7_SMBA_FUNC1_IDX12_PINMUX_PG(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 12) /* SMBA function for IIC 7 */
#define UART7_TXD_FUNC1_IDX13_PINMUX_PG(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 13) /* TX data function for UART 7 */
#define UART7_RXD_FUNC1_IDX14_PINMUX_PG(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 14) /* RX data function for UART 7 */
#define UART7_CTS_N_FUNC1_IDX15_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 15) /* CTS function for UART 7 */
#define UART7_DSR_N_FUNC1_IDX16_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 16) /* DSR function for UART 7 */
#define UART7_DCD_N_FUNC1_IDX17_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 17) /* DCD function for UART 7 */
#define UART7_RI_N_FUNC1_IDX18_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 18) /* RI function for UART 7 */
#define UART7_RTS_N_FUNC1_IDX19_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 19) /* RTS function for UART 7 */
#define UART7_DTR_N_FUNC1_IDX20_PINMUX_PG(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 20) /* DTR function for UART 7 */
#define UART7_DE_FUNC1_IDX21_PINMUX_PG(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 21) /* DE function for UART 7 */
#define UART7_RE_FUNC1_IDX22_PINMUX_PG(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 22) /* RE function for UART 7 */
#define FDCAN_TXD_FUNC1_IDX23_PINMUX_PG(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 23) /* TX data of CAN */
#define FDCAN_RXD_FUNC1_IDX24_PINMUX_PG(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 24) /* RX data of CAN */
#define PS2IF1_CLK_FUNC1_IDX25_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 25) /* ps2if1 clock */
#define PS2IF1_DAT_FUNC1_IDX26_PINMUX_PG(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 26) /* ps2if1 dat */
#define PWM7_FUNC1_IDX27_PINMUX_PG(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 27) /* pwm7 */
#define CAP7_FUNC1_IDX28_PINMUX_PG(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 28) /* cap7 */
#define OWM_FUNC1_IDX29_PINMUX_PG(XX)             GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 29) /* owm */
#define CEC_FUNC1_IDX30_PINMUX_PG(XX)             GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 30) /* cec */
#define PIS_CH5_FUNC1_IDX31_PINMUX_PG(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PG, XX, 31) /* PIS channel 5 output */
#define ADTIM2_CH1_FUNC1_IDX01_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 1)  /* positive function of channel 1 of ADTIM2 */
#define ADTIM2_CH1N_FUNC1_IDX02_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 2)  /* negative function of channel 1 of ADTIM2 */
#define ADTIM2_CH2_FUNC1_IDX03_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 3)  /* positive function of channel 2 of ADTIM2 */
#define ADTIM2_CH2N_FUNC1_IDX04_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 4)  /* negative function of channel 2 of ADTIM2 */
#define ADTIM2_CH3_FUNC1_IDX05_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 5)  /* positive function of channel 3 of ADTIM2 */
#define ADTIM2_CH3N_FUNC1_IDX06_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 6)  /* negative function of channel 3 of ADTIM2 */
#define ADTIM2_CH4_FUNC1_IDX07_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 7)  /* positive function of channel 4 of ADTIM2 */
#define ADTIM2_ETR_FUNC1_IDX08_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 8)  /* external trigger function of ADTIM2 */
#define ADTIM2_BK_FUNC1_IDX09_PINMUX_PH(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 9)  /* break function of ADTIM2 */
#define I2C8_SCL_FUNC1_IDX10_PINMUX_PH(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 10) /* SCL function for IIC 8 */
#define I2C8_SDA_FUNC1_IDX11_PINMUX_PH(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 11) /* SDA function for IIC 8 */
#define I2C8_SMBA_FUNC1_IDX12_PINMUX_PH(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 12) /* SMBA function for IIC 8 */
#define UART8_TXD_FUNC1_IDX13_PINMUX_PH(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 13) /* TX data function for UART 8 */
#define UART8_RXD_FUNC1_IDX14_PINMUX_PH(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 14) /* RX data function for UART 8 */
#define UART8_CTS_N_FUNC1_IDX15_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 15) /* CTS function for UART 8 */
#define UART8_DSR_N_FUNC1_IDX16_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 16) /* DSR function for UART 8 */
#define UART8_DCD_N_FUNC1_IDX17_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 17) /* DCD function for UART 8 */
#define UART8_RI_N_FUNC1_IDX18_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 18) /* RI function for UART 8 */
#define UART8_RTS_N_FUNC1_IDX19_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 19) /* RTS function for UART 8 */
#define UART8_DTR_N_FUNC1_IDX20_PINMUX_PH(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 20) /* DTR function for UART 8 */
#define UART8_DE_FUNC1_IDX21_PINMUX_PH(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 21) /* DE function for UART 8 */
#define UART8_RE_FUNC1_IDX22_PINMUX_PH(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 22) /* RE function for UART 8 */
#define USB1_DP_FUNC1_IDX23_PINMUX_PH(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 23) /* DP function of USB1 */
#define USB1_DM_FUNC1_IDX24_PINMUX_PH(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 24) /* DM function of USB1 */
#define USB1_CID_FUNC1_IDX25_PINMUX_PH(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 25) /* CID function of USB1 */
#define PS2IF2_CLK_FUNC1_IDX26_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 26) /* ps2if2 clock */
#define PS2IF2_DAT_FUNC1_IDX27_PINMUX_PH(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 27) /* ps2if2 dat */
#define PWM2_FUNC1_IDX28_PINMUX_PH(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 28) /* pwm2 */
#define PWM4_FUNC1_IDX29_PINMUX_PH(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 29) /* pwm4 */
#define DBG_CACHE2_MISS_FUNC1_IDX30_PINMUX_PH(XX) GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 30) /* cache2 miss test output */
#define DBG_CACHE2_HIT_FUNC1_IDX31_PINMUX_PH(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PH, XX, 31) /* cache2 hit test output */
#define GPTIMA1_CH1_FUNC1_IDX01_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 1)  /* channel 1 of GPTIMA */
#define GPTIMA1_CH2_FUNC1_IDX02_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 2)  /* channel 2 of GPTIMA */
#define GPTIMA1_CH3_FUNC1_IDX03_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 3)  /* channel 3 of GPTIMA */
#define GPTIMA1_CH4_FUNC1_IDX04_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 4)  /* channel 4 of GPTIMA */
#define GPTIMA1_ETR_FUNC1_IDX05_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 5)  /* external trigger function of GPTIMA */
#define I2C9_SCL_FUNC1_IDX06_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 6)  /* SCL function for IIC 9 */
#define I2C9_SDA_FUNC1_IDX07_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 7)  /* SDA function for IIC 9 */
#define I2C9_SMBA_FUNC1_IDX08_PINMUX_PI(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 8)  /* SMBA function for IIC 9 */
#define UART9_TXD_FUNC1_IDX09_PINMUX_PI(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 9)  /* TX data function for UART 3 */
#define UART9_RXD_FUNC1_IDX10_PINMUX_PI(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 10) /* RX data function for UART 3 */
#define UART9_CTS_N_FUNC1_IDX11_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 11) /* CTS function for UART 3 */
#define UART9_DSR_N_FUNC1_IDX12_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 12) /* DSR function for UART 3 */
#define UART9_DCD_N_FUNC1_IDX13_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 13) /* DCD function for UART 3 */
#define UART9_RI_N_FUNC1_IDX14_PINMUX_PI(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 14) /* RI function for UART 3 */
#define UART9_RTS_N_FUNC1_IDX15_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 15) /* RTS function for UART 3 */
#define UART9_DTR_N_FUNC1_IDX16_PINMUX_PI(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 16) /* DTR function for UART 3 */
#define UART9_DE_FUNC1_IDX17_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 17) /* DE function for UART 3 */
#define UART9_RE_FUNC1_IDX18_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 18) /* RE function for UART 3 */
#define SPI1_SCK_FUNC1_IDX19_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 19) /* SCK function for SPI 1 */
#define SPI1_NSS_FUNC1_IDX20_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 20) /* chip select function for SPI 1 */
#define SPI1_MOSI_FUNC1_IDX21_PINMUX_PI(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 21) /* MOSI function for SPI 1 */
#define SPI1_MISO_FUNC1_IDX22_PINMUX_PI(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 22) /* MISO function for SPI 1 */
#define SPI1_I2S_FUNC1_IDX23_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 23) /* IIS clock function of SPI 1 */
#define USB1_DP_FUNC1_IDX24_PINMUX_PI(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 24) /* DP function of USB1 */
#define USB1_DM_FUNC1_IDX25_PINMUX_PI(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 25) /* DM function of USB1 */
#define USB1_CID_FUNC1_IDX26_PINMUX_PI(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 26) /* CID function of USB1 */
#define PWM9_FUNC1_IDX27_PINMUX_PI(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 27) /* pwm9 */
#define PWM10_FUNC1_IDX28_PINMUX_PI(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 28) /* pwm10 */
#define CAP9_FUNC1_IDX29_PINMUX_PI(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 29) /* cap9 */
#define CAP10_FUNC1_IDX30_PINMUX_PI(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 30) /* cap10 */
#define PIS_CH6_FUNC1_IDX31_PINMUX_PI(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PI, XX, 31) /* PIS channel 6 output */
#define GPTIMA2_CH1_FUNC1_IDX01_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 1)  /* channel 1 of GPTIMA */
#define GPTIMA2_CH2_FUNC1_IDX02_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 2)  /* channel 2 of GPTIMA */
#define GPTIMA2_CH3_FUNC1_IDX03_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 3)  /* channel 3 of GPTIMA */
#define GPTIMA2_CH4_FUNC1_IDX04_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 4)  /* channel 4 of GPTIMA */
#define GPTIMA2_ETR_FUNC1_IDX05_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 5)  /* external trigger function of GPTIMA */
#define I2C10_SCL_FUNC1_IDX06_PINMUX_PJ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 6)  /* SCL function for IIC 10 */
#define I2C10_SDA_FUNC1_IDX07_PINMUX_PJ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 7)  /* SDA function for IIC 10 */
#define I2C10_SMBA_FUNC1_IDX08_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 8)  /* SMBA function for IIC 10 */
#define UART10_TXD_FUNC1_IDX09_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 9)  /* TX data function for UART 10 */
#define UART10_RXD_FUNC1_IDX10_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 10) /* RX data function for UART 10 */
#define UART10_CTS_N_FUNC1_IDX11_PINMUX_PJ(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 11) /* CTS function for UART 10 */
#define UART10_DSR_N_FUNC1_IDX12_PINMUX_PJ(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 12) /* DSR function for UART 10 */
#define UART10_DCD_N_FUNC1_IDX13_PINMUX_PJ(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 13) /* DCD function for UART 10 */
#define UART10_RI_N_FUNC1_IDX14_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 14) /* RI function for UART 10 */
#define UART10_RTS_N_FUNC1_IDX15_PINMUX_PJ(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 15) /* RTS function for UART 10 */
#define UART10_DTR_N_FUNC1_IDX16_PINMUX_PJ(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 16) /* DTR function for UART 10 */
#define UART10_DE_FUNC1_IDX17_PINMUX_PJ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 17) /* DE function for UART 10 */
#define UART10_RE_FUNC1_IDX18_PINMUX_PJ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 18) /* RE function for UART 10 */
#define SPI2_SCK_FUNC1_IDX19_PINMUX_PJ(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 19) /* SCK function for SPI 2 */
#define SPI2_NSS_FUNC1_IDX20_PINMUX_PJ(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 20) /* chip select function for SPI 2 */
#define SPI2_MOSI_FUNC1_IDX21_PINMUX_PJ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 21) /* MOSI function for SPI 2 */
#define SPI2_MISO_FUNC1_IDX22_PINMUX_PJ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 22) /* MISO function for SPI 2 */
#define SPI2_I2S_FUNC1_IDX23_PINMUX_PJ(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 23) /* IIS clock function of SPI 2 */
#define MJTAG1_TRST_FUNC1_IDX24_PINMUX_PJ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 24) /* jtag master 1 trst */
#define MJTAG1_TDI_FUNC1_IDX25_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 25) /* jtag master 1 tdi */
#define MJTAG1_TCK_FUNC1_IDX26_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 26) /* jtag master 1 tck */
#define MJTAG1_TMS_FUNC1_IDX27_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 27) /* jtag master 1 tms */
#define MJTAG1_TDO_FUNC1_IDX28_PINMUX_PJ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 28) /* jtag master 1 tdo */
#define DBG_SCL1_FUNC1_IDX29_PINMUX_PJ(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 29) /* I2C Debug SCL1 */
#define DBG_SDA1_FUNC1_IDX30_PINMUX_PJ(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 30) /* I2C Debug SDA1 */
#define PIS_CH7_FUNC1_IDX31_PINMUX_PJ(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PJ, XX, 31) /* PIS channel 7 output */
#define GPTIMB1_CH1_FUNC1_IDX01_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 1)  /* channel 1 of GPTIMB */
#define GPTIMB1_CH2_FUNC1_IDX02_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 2)  /* channel 2 of GPTIMB */
#define GPTIMB1_CH3_FUNC1_IDX03_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 3)  /* channel 3 of GPTIMB */
#define GPTIMB1_CH4_FUNC1_IDX04_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 4)  /* channel 4 of GPTIMB */
#define GPTIMB1_ETR_FUNC1_IDX05_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 5)  /* external trigger function of GPTIMB */
#define I2C11_SCL_FUNC1_IDX06_PINMUX_PK(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 6)  /* SCL function for IIC 11 */
#define I2C11_SDA_FUNC1_IDX07_PINMUX_PK(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 7)  /* SDA function for IIC 11 */
#define I2C11_SMBA_FUNC1_IDX08_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 8)  /* SMBA function for IIC 11 */
#define LTPI_TEST_CLK_FUNC1_IDX09_PINMUX_PK(XX)   GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 9)  /* ltpi test clock output */
#define DBG_CACHE1_MISS_FUNC1_IDX10_PINMUX_PK(XX) GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 10) /* cache1 miss test output */
#define DBG_CACHE1_HIT_FUNC1_IDX11_PINMUX_PK(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 11) /* cache1 hit test output */
#define UART11_TXD_FUNC1_IDX12_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 12) /* TX data function for UART 11 */
#define UART11_RXD_FUNC1_IDX13_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 13) /* RX data function for UART 11 */
#define UART11_CTS_N_FUNC1_IDX14_PINMUX_PK(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 14) /* CTS function for UART 11 */
#define UART11_DSR_N_FUNC1_IDX15_PINMUX_PK(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 15) /* DSR function for UART 11 */
#define UART11_DCD_N_FUNC1_IDX16_PINMUX_PK(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 16) /* DCD function for UART 11 */
#define UART11_RI_N_FUNC1_IDX17_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 17) /* RI function for UART 11 */
#define UART11_RTS_N_FUNC1_IDX18_PINMUX_PK(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 18) /* RTS function for UART 11 */
#define UART11_DTR_N_FUNC1_IDX19_PINMUX_PK(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 19) /* DTR function for UART 11 */
#define UART11_DE_FUNC1_IDX20_PINMUX_PK(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 20) /* DE function for UART 11 */
#define UART11_RE_FUNC1_IDX21_PINMUX_PK(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 21) /* RE function for UART 11 */
#define MJTAG2_TRST_FUNC1_IDX22_PINMUX_PK(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 22) /* jtag master 2 trst */
#define MJTAG2_TDI_FUNC1_IDX23_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 23) /* jtag master 2 tdi */
#define MJTAG2_TCK_FUNC1_IDX24_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 24) /* jtag master 2 tck */
#define MJTAG2_TMS_FUNC1_IDX25_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 25) /* jtag master 2 tms */
#define MJTAG2_TDO_FUNC1_IDX26_PINMUX_PK(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 26) /* jtag master 2 tdo */
#define DBG_SCL2_FUNC1_IDX27_PINMUX_PK(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 27) /* I2C Debug SCL2 */
#define DBG_SDA2_FUNC1_IDX28_PINMUX_PK(XX)        GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 28) /* I2C Debug SDA2 */
#define PWM7_FUNC1_IDX29_PINMUX_PK(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 29) /* pwm7 */
#define CAP7_FUNC1_IDX30_PINMUX_PK(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 30) /* cap7 */
#define PIS_CH8_FUNC1_IDX31_PINMUX_PK(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PK, XX, 31) /* PIS channel 8 output */
#define GPTIMC1_CH1_FUNC1_IDX01_PINMUX_PM(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 1)  /* positive function of channel 1 of GPTIMC */
#define GPTIMC1_CH1N_FUNC1_IDX02_PINMUX_PM(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 2)  /* negative function of channel 1 of GPTIMC */
#define GPTIMC1_CH2_FUNC1_IDX03_PINMUX_PM(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 3)  /* positive function of channel 2 of GPTIMC */
#define GPTIMC1_BK_FUNC1_IDX04_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 4)  /* break function of GPTIMC */
#define I2C12_SCL_FUNC1_IDX05_PINMUX_PM(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 5)  /* SCL function for IIC 12 */
#define I2C12_SDA_FUNC1_IDX06_PINMUX_PM(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 6)  /* SDA function for IIC 12 */
#define I2C12_SMBA_FUNC1_IDX07_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 7)  /* SMBA function for IIC 12 */
#define EMMC2_LED_CTRL_FUNC1_IDX08_PINMUX_PM(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 8)  /* SD card communication indicator led */
#define EMMC1_LED_CTRL_FUNC1_IDX09_PINMUX_PM(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 9)  /* SD card communication indicator led */
#define DBG_SRC_CLK_FUNC1_IDX10_PINMUX_PM(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 10) /* HBUS clock test output */
#define UART12_TXD_FUNC1_IDX11_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 11) /* TX data function for UART 12 */
#define UART12_RXD_FUNC1_IDX12_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 12) /* RX data function for UART 12 */
#define UART12_CTS_N_FUNC1_IDX13_PINMUX_PM(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 13) /* CTS function for UART 12 */
#define UART12_DSR_N_FUNC1_IDX14_PINMUX_PM(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 14) /* DSR function for UART 12 */
#define UART12_DCD_N_FUNC1_IDX15_PINMUX_PM(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 15) /* DCD function for UART 12 */
#define UART12_RI_N_FUNC1_IDX16_PINMUX_PM(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 16) /* RI function for UART 12 */
#define UART12_RTS_N_FUNC1_IDX17_PINMUX_PM(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 17) /* RTS function for UART 12 */
#define UART12_DTR_N_FUNC1_IDX18_PINMUX_PM(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 18) /* DTR function for UART 12 */
#define UART12_DE_FUNC1_IDX19_PINMUX_PM(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 19) /* DE function for UART 12 */
#define UART12_RE_FUNC1_IDX20_PINMUX_PM(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 20) /* RE function for UART 12 */
#define MJTAG3_TRST_FUNC1_IDX21_PINMUX_PM(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 21) /* jtag master 3 trst */
#define MJTAG3_TDI_FUNC1_IDX22_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 22) /* jtag master 3 tdi */
#define MJTAG3_TCK_FUNC1_IDX23_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 23) /* jtag master 3 tck */
#define MJTAG3_TMS_FUNC1_IDX24_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 24) /* jtag master 3 tms */
#define MJTAG3_TDO_FUNC1_IDX25_PINMUX_PM(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 25) /* jtag master 3 tdo */
#define PWM8_FUNC1_IDX26_PINMUX_PM(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 26) /* pwm8 */
#define PWM9_FUNC1_IDX27_PINMUX_PM(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 27) /* pwm9 */
#define PWM10_FUNC1_IDX28_PINMUX_PM(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 28) /* pwm10 */
#define CAP8_FUNC1_IDX29_PINMUX_PM(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 29) /* cap8 */
#define CAP9_FUNC1_IDX30_PINMUX_PM(XX)            GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 30) /* cap9 */
#define CAP10_FUNC1_IDX31_PINMUX_PM(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PM, XX, 31) /* cap10 */
#define ADTIM1_CH1_FUNC1_IDX01_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 1)  /* positive function of channel 1 of ADTIM1 */
#define ADTIM1_CH1N_FUNC1_IDX02_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 2)  /* negative function of channel 1 of ADTIM1 */
#define ADTIM1_CH2_FUNC1_IDX03_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 3)  /* positive function of channel 2 of ADTIM1 */
#define ADTIM1_CH2N_FUNC1_IDX04_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 4)  /* negative function of channel 2 of ADTIM1 */
#define ADTIM1_CH3_FUNC1_IDX05_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 5)  /* positive function of channel 3 of ADTIM1 */
#define ADTIM1_CH3N_FUNC1_IDX06_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 6)  /* negative function of channel 3 of ADTIM1 */
#define ADTIM1_CH4_FUNC1_IDX07_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 7)  /* positive function of channel 4 of ADTIM1 */
#define ADTIM1_ETR_FUNC1_IDX08_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 8)  /* external trigger function of ADTIM1 */
#define ADTIM1_BK_FUNC1_IDX09_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 9)  /* break function of ADTIM1 */
#define I2C13_SCL_FUNC1_IDX10_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 10) /* SCL function for IIC 13 */
#define I2C13_SDA_FUNC1_IDX11_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 11) /* SDA function for IIC 13 */
#define I2C13_SMBA_FUNC1_IDX12_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 12) /* SMBA function for IIC 13 */
#define I2C14_SCL_FUNC1_IDX13_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 13) /* SCL function for IIC 14 */
#define I2C14_SDA_FUNC1_IDX14_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 14) /* SDA function for IIC 14 */
#define I2C14_SMBA_FUNC1_IDX15_PINMUX_PN(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 15) /* SMBA function for IIC 14 */
#define UART1_TXD_FUNC1_IDX16_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 16) /* TX data function for UART 1 */
#define UART1_RXD_FUNC1_IDX17_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 17) /* RX data function for UART 1 */
#define UART1_CTS_N_FUNC1_IDX18_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 18) /* CTS function for UART 1 */
#define UART1_RTS_N_FUNC1_IDX19_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 19) /* RTS function for UART 1 */
#define UART3_TXD_FUNC1_IDX20_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 20) /* TX data function for UART 3 */
#define UART3_RXD_FUNC1_IDX21_PINMUX_PN(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 21) /* RX data function for UART 3 */
#define UART3_CTS_N_FUNC1_IDX22_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 22) /* CTS function for UART 3 */
#define UART3_RTS_N_FUNC1_IDX23_PINMUX_PN(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 23) /* RTS function for UART 3 */
#define PWM11_FUNC1_IDX24_PINMUX_PN(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 24) /* pwm11 */
#define PWM12_FUNC1_IDX25_PINMUX_PN(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 25) /* pwm12 */
#define PWM13_FUNC1_IDX26_PINMUX_PN(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 26) /* pwm13 */
#define CAP11_FUNC1_IDX27_PINMUX_PN(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 27) /* cap11 */
#define CAP12_FUNC1_IDX28_PINMUX_PN(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 28) /* cap12 */
#define CAP13_FUNC1_IDX29_PINMUX_PN(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 29) /* cap13 */
#define PIS_CH5_FUNC1_IDX30_PINMUX_PN(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 30) /* PIS channel 5 output */
#define PIS_CH6_FUNC1_IDX31_PINMUX_PN(XX)         GEN_PINMUX_PXYY(PINMUX_FUNC1, PN, XX, 31) /* PIS channel 6 output */
#define ADTIM2_CH1_FUNC1_IDX01_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 1)  /* positive function of channel 1 of ADTIM2 */
#define ADTIM2_CH1N_FUNC1_IDX02_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 2)  /* negative function of channel 1 of ADTIM2 */
#define ADTIM2_CH2_FUNC1_IDX03_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 3)  /* positive function of channel 2 of ADTIM2 */
#define ADTIM2_CH2N_FUNC1_IDX04_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 4)  /* negative function of channel 2 of ADTIM2 */
#define ADTIM2_CH3_FUNC1_IDX05_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 5)  /* positive function of channel 3 of ADTIM2 */
#define ADTIM2_CH3N_FUNC1_IDX06_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 6)  /* negative function of channel 3 of ADTIM2 */
#define ADTIM2_CH4_FUNC1_IDX07_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 7)  /* positive function of channel 4 of ADTIM2 */
#define ADTIM2_ETR_FUNC1_IDX08_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 8)  /* external trigger function of ADTIM2 */
#define ADTIM2_BK_FUNC1_IDX09_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 9)  /* break function of ADTIM2 */
#define I2C15_SCL_FUNC1_IDX10_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 10) /* SCL function for IIC 15 */
#define I2C15_SDA_FUNC1_IDX11_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 11) /* SDA function for IIC 15 */
#define I2C15_SMBA_FUNC1_IDX12_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 12) /* SMBA function for IIC 15 */
#define I2C16_SCL_FUNC1_IDX13_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 13) /* SCL function for IIC 16 */
#define I2C16_SDA_FUNC1_IDX14_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 14) /* SDA function for IIC 16 */
#define I2C16_SMBA_FUNC1_IDX15_PINMUX_PQ(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 15) /* SMBA function for IIC 16 */
#define UART2_TXD_FUNC1_IDX16_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 16) /* TX data function for UART 2 */
#define UART2_RXD_FUNC1_IDX17_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 17) /* RX data function for UART 2 */
#define UART2_CTS_N_FUNC1_IDX18_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 18) /* CTS function for UART 2 */
#define UART2_RTS_N_FUNC1_IDX19_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 19) /* RTS function for UART 2 */
#define UART4_TXD_FUNC1_IDX20_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 20) /* TX data function for UART 4 */
#define UART4_RXD_FUNC1_IDX21_PINMUX_PQ(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 21) /* RX data function for UART 4 */
#define UART4_CTS_N_FUNC1_IDX22_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 22) /* CTS function for UART 4 */
#define UART4_RTS_N_FUNC1_IDX23_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 23) /* RTS function for UART 4 */
#define PWM14_FUNC1_IDX24_PINMUX_PQ(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 24) /* pwm14 */
#define PWM15_FUNC1_IDX25_PINMUX_PQ(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 25) /* pwm15 */
#define PWM16_FUNC1_IDX26_PINMUX_PQ(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 26) /* pwm16 */
#define CAP14_FUNC1_IDX27_PINMUX_PQ(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 27) /* cap14 */
#define CAP15_FUNC1_IDX28_PINMUX_PQ(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 28) /* cap15 */
#define CAP16_FUNC1_IDX29_PINMUX_PQ(XX)           GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 29) /* cap16 */
#define USB20_DBG14_FUNC1_IDX30_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 30)
#define USB20_DBG15_FUNC1_IDX31_PINMUX_PQ(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PQ, XX, 31)
#define PARAL_DATA0_FUNC1_IDX01_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 1) 
#define PARAL_DATA1_FUNC1_IDX02_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 2) 
#define PARAL_DATA2_FUNC1_IDX03_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 3) 
#define PARAL_DATA3_FUNC1_IDX04_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 4) 
#define PARAL_DATA4_FUNC1_IDX05_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 5) 
#define PARAL_DATA5_FUNC1_IDX06_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 6) 
#define PARAL_DATA6_FUNC1_IDX07_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 7) 
#define PARAL_DATA7_FUNC1_IDX08_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 8) 
#define PARAL_PERROR_FUNC1_IDX09_PINMUX_PT(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 9) 
#define PARAL_XFLAG_FUNC1_IDX10_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 10)
#define PARAL_BUSY_FUNC1_IDX11_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 11)
#define PARAL_FAULT_FUNC1_IDX12_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 12)
#define PARAL_ACK_FUNC1_IDX13_PINMUX_PT(XX)       GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 13)
#define PARAL_STROBE_FUNC1_IDX14_PINMUX_PT(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 14)
#define PARAL_AUTOFD_FUNC1_IDX15_PINMUX_PT(XX)    GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 15)
#define PARAL_INIT_FUNC1_IDX16_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 16)
#define PARAL_SELECTIN_FUNC1_IDX17_PINMUX_PT(XX)  GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 17)
#define USB20_DBG0_FUNC1_IDX18_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 18)
#define USB20_DBG1_FUNC1_IDX19_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 19)
#define USB20_DBG2_FUNC1_IDX20_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 20)
#define USB20_DBG3_FUNC1_IDX21_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 21)
#define USB20_DBG4_FUNC1_IDX22_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 22)
#define USB20_DBG5_FUNC1_IDX23_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 23)
#define USB20_DBG6_FUNC1_IDX24_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 24)
#define USB20_DBG7_FUNC1_IDX25_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 25)
#define USB20_DBG8_FUNC1_IDX26_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 26)
#define USB20_DBG9_FUNC1_IDX27_PINMUX_PT(XX)      GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 27)
#define USB20_DBG10_FUNC1_IDX28_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 28)
#define USB20_DBG11_FUNC1_IDX29_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 29)
#define USB20_DBG12_FUNC1_IDX30_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 30)
#define USB20_DBG13_FUNC1_IDX31_PINMUX_PT(XX)     GEN_PINMUX_PXYY(PINMUX_FUNC1, PT, XX, 31)

#endif
