if (NOT DEFINED BOARD_REVISION)
  set(BOARD_REVISION "zynq")
else ()
  if (NOT (BOARD_REVISION STREQUAL "zynq") AND NOT (BOARD_REVISION STREQUAL "acku"))
    message(FATAL_ERROR "Invalid board revision, ${BOARD_REVISION}, valid revisions are: zynq, acku")
  endif()
endif()
