# CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.1.123"
CONFIG_NET_CONFIG_MY_IPV4_ADDR="10.10.20.134"
CONFIG_MDIO=y
CONFIG_MDIO_SHELL=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NET_PKT_RX_COUNT=256
CONFIG_NET_PKT_TX_COUNT=256
CONFIG_NET_BUF_RX_COUNT=64
CONFIG_NET_BUF_TX_COUNT=24
CONFIG_NET_BUF_DATA_SIZE=1024
# CONFIG_NET_TCP_MAX_RECV_WINDOW_SIZE=20480
CONFIG_DWMAC_NB_TX_DESCS=24
CONFIG_DWMAC_NB_RX_DESCS=48
# CONFIG_COMPILER_OPT="-O3"
CONFIG_THREAD_ANALYZER=y
# CONFIG_NET_PHY_FORCE_100M=y
# CONFIG_NUM_COOP_PRIORITIES=0
CONFIG_NET_TC_THREAD_PRIO_CUSTOM=y
CONFIG_NET_TC_RX_THREAD_BASE_PRIO=5
CONFIG_NET_TC_TX_THREAD_BASE_PRIO=4
# CONFIG_NET_SOCKETS_SERVICE_THREAD_PRIO=6
CONFIG_PRECISE_EXCEPTION=n
