# 启用MP5023驱动
CONFIG_MP5023=y
CONFIG_MP5023_DEFAULT_PAGE=0
CONFIG_MP5023_TIMEOUT_MS=100
CONFIG_MP5023_PEC_EN=y

# 启用I2C
CONFIG_I2C=y
CONFIG_SMBUS=y
#CONFIG_PMBUS=y
#CONFIG_I2C_BITRATE_FAST=y

# 启用传感器子系统
CONFIG_SENSOR=y

# 启用日志
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_SENSOR_LOG_LEVEL_DBG=y