#ifndef _MBEDTLS_LS_CFG_ALT_
#define _MBEDTLS_LS_CFG_ALT_

#if defined(CONFIG_MBEDTLS_CIPHER_AES_LINKEDSEMI)
#define MBEDTLS_AES_ALT
#endif

#if defined(CONFIG_MBEDTLS_ECDSA_SECP256R1_SECP384R1_SM2_LINKEDSEMI_OTBN_ALT)||defined(CONFIG_MBEDTLS_LINKEDSEMI_OTBN_DELEGATION_CLIENT)
#define MBEDTLS_ECDSA_SIGN_ALT
#define MBEDTLS_ECDSA_VERIFY_ALT
#define MBEDTLS_ECDSA_GENKEY_ALT
#endif

#if defined(CONFIG_MBEDTLS_SHA224_SHA256_SM3_LINKEDSEMI_HARDWARE_ALT)||defined(CONFIG_MBEDTLS_SHA256_SM3_LINKEDSEMI_OTBN_ALT)
#define MBEDTLS_SHA256_ALT
#endif

#if defined(CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_HARDWARE_ALT)||defined(CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_OTBN_ALT)
#define MBEDTLS_SHA512_ALT
#endif

#if defined(CONFIG_MBEDTLS_RSA_LINKEDSEMI_OTBN_ALT)
#define MBEDTLS_RSA_OTBN_HOOK
#endif

#if defined(CONFIG_MBEDTLS_THREADING_LINKEDSEMI_ALT)
#define MBEDTLS_THREADING_ALT
#define MBEDTLS_THREADING_C
#endif

#endif /*_MBEDTLS_LS_CFG_ALT_*/