CONFIG_GPIO=y
CONFIG_GPIO_LINKEDSEMI_SGPIOM=n

CONFIG_I2C=y
CONFIG_I2C_TARGET=y
CONFIG_EEPROM=y

CONFIG_ESPI=y
CONFIG_KCS=y
CONFIG_IPMI=y

CONFIG_SHELL=y

CONFIG_PECI=y
CONFIG_SHELL_STACK_SIZE=10240
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=10240

CONFIG_HW_STACK_PROTECTION=y
