[common]
# support usb/inband/outband
channel = outband
physical_port = 
uart_port = 
vid = 0x2fe3
pid = 0x7

bmc_ip = 192.168.68.60
username = taobao
password = 9ijn0okm
ciphersuite = 17

arottool_version = v2.5.3